# WEB SCRAPING
* Web scraping refers to the process of automatically extracting data from websites. It involves writing code or using software tools to access and parse the HTML or other structured data of a webpage, extracting the desired information, and storing it for further analysis or use.

* Web scraping allows you to gather data from multiple web pages in a structured format, which can be useful for various purposes such as data analysis, market research, price comparison, content aggregation, and monitoring changes on websites, among others.

###### The basic steps involved in web scraping are as follows:

* Sending an HTTP request to the target website's server to retrieve the HTML content of the webpage.
* Parsing the HTML content to extract the relevant data using techniques like XPath, CSS selectors, or regular expressions.
* Cleaning and transforming the extracted data into a structured format that can be used for analysis or storage.
* Storing the extracted data in a desired format, such as a CSV file, JSON file, or a database.

### importing libraries

In [ ]:
 
import requests  
from bs4 import BeautifulSoup
import pandas as pd

In [16]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage1=requests.get("https://www.zomato.com/bangalore",headers=headers).text

In [3]:
soup=BeautifulSoup(webpage1,"lxml")

In [52]:
urlls = soup.find_all('a', href=True)  # Find all <a> tags with the href attribute

for url in urlls:
    print(url['href'])  # Print the value of the href attribute

/bangalore/restaurants?place_name=Bengaluru&dishv2_id=30308
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=68987
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=55280
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=35013
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=35301
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=10296
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=9055
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=35798
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=12025
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=56691
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=39212
/bangalore/restaurants?place_name=Bengaluru&dishv2_id=19315
/bangalore/savoury-restaurant-1-frazer-town/order
/bangalore/savoury-restaurant-1-frazer-town/order
/bangalore/thoms-bakery-since-1970-frazer-town-bangalore/order
/bangalore/thoms-bakery-since-1970-frazer-town-bangalore/order
/bangalore/thalairaj-biryani-indiranagar-bangalore/order
/bangalore/thalairaj-biryani-indiranagar-bangalore/order
/bangalore/truffles-2-st-marks-road/order
/bangalore/truffles-2-st-marks-road/order
/bangalore/dominos-pizza-1-mg-road/order
/bangalore/dominos-pizza-1-mg-road/order
/bangalore/goila-butter-chicken-koramangala-6th-block-bangalore/order
/bangalore/goila-butter-chicken-koramangala-6th-block-bangalore/order
/bangalore/nandhini-deluxe-st-marks-road-bangalore/order
/bangalore/nandhini-deluxe-st-marks-road-bangalore/order
/bangalore/savoury-sea-shell-restaurant-btm-bangalore/order
/bangalore/savoury-sea-shell-restaurant-btm-bangalore/order
/bangalore/empire-restaurant-shivajinagar-bangalore/order
/bangalore/empire-restaurant-shivajinagar-bangalore/order
/bangalore/collections
/bangalore/rooftop
/bangalore/trending-this-week
/bangalore/picturesque-cafes
/bangalore/newly-opened
/bangalore/collections
https://www.zomato.com/bangalore/indiranagar-restaurants
https://www.zomato.com/bangalore/marathahalli-restaurants
https://www.zomato.com/bangalore/whitefield-restaurants
https://www.zomato.com/bangalore/koramangala-5th-block-restaurants
https://www.zomato.com/bangalore/hsr-restaurants
https://www.zomato.com/bangalore/jayanagar-restaurants
https://www.zomato.com/bangalore/jp-nagar-restaurants
https://www.zomato.com/bangalore/sarjapur-road-restaurants
https://www.zomato.com/who-we-are
https://blog.zomato.com/
https://www.zomato.com/careers
https://www.zomato.com/investor-relations
https://www.zomato.com/report-fraud
https://www.zomato.com/contact
https://www.zomato.com/
https://www.blinkit.com/
https://www.feedingindia.org/
https://www.hyperpure.com/
https://www.zomato.com/zomaland
https://www.zomato.com/partner_with_us
https://play.google.com/store/apps/details?id=com.application.services.partner&hl=en_IN&gl=US
https://www.zomato.com/enterprise-solutions
https://www.zomato.com/privacy
https://www.zomato.com/security
https://www.zomato.com/conditions
https://www.zomato.com/directory
https://in.linkedin.com/company/zomato
https://www.instagram.com/zomato/
https://twitter.com/zomato
https://www.youtube.com/zomato
https://www.facebook.com/zomato
https://bnc.lt/download-zomato-ios
https://bnc.lt/download-z-android

In [ ]:
 cuisines_.append(cuisines)
        except:
            cuisines_.appned(0)

In [5]:
#all the information is stored in this hmtl about the food menu and price 
#as we sorted this code in items 

items=soup.find_all('div',class_="sc-1s0saks-11 cYGeYt")

In [ ]:
<div class="sc-fgfRvd gBMRZZ"><span><a href="https://www.zomato.com/hyderabad/restaurants/biryani/" class="sc-hIVACf hAtIrI">Biryani</a><span>, </span></span><span><a href="https://www.zomato.com/hyderabad/restaurants/hyderabadi/" class="sc-hIVACf hAtIrI">Hyderabadi</a><span>, </span></span><span><a href="https://www.zomato.com/hyderabad/restaurants/north-indian/" class="sc-hIVACf hAtIrI">North Indian</a><span>, </span></span><span><a href="https://www.zomato.com/hyderabad/restaurants/chinese/" class="sc-hIVACf hAtIrI">Chinese</a></span></div>

In [ ]:
tag_list = items.find_all('div', class_="sc-fgfRvd gBMRZZ")
tags = []  # Initialize an empty list to store the tags
for tag in tag_list:
    spans = tag.find_all('span')
    text = ''.join(span.text for span in spans)
    tags.append(text if text else "non")

In [ ]:
 tag_list = item.find_all('a', class_="sc-hIVACf hAtIrI")
         for tag in tag_list:
            tags.append(tag.text if tag.text else "non")

In [14]:
tags = []  # Initialize an empty list to store the tags
for item in items:
    tag_list = item.find_all('div', class_="sc-fgfRvd gBMRZZ")
    for tag in tag_list:
        spans = tag.find_all('span')
        text = ''.join(span.text for span in spans)
        tags.append(text if text else "non")

In [15]:
tags

[]

In [39]:
#this code will retrieve the restaurant from the url provide about 
restaurant_name=soup.find('h1',class_="sc-7kepeu-0 sc-iSDuPN fwzNdh")
print(restaurant_name.text)

Dindigul Veetu Kalyanam

In [25]:
#this code will retrieve the first tag of restaurant from the url provide about 
tags=soup.find_all('a',class_="sc-hIVACf hAtIrI")
#has there are more than one tags we can apply the print(tags.text) it wont work 
#we must run a for loop here 
for tag in tags:
    print(tag.text)

Biryani

In [67]:
#here this hmtl 'a' contain both place and city names but we need only place name 
#we need split on ',' and get zeroth item 
address = soup.find('a', class_="sc-clNaTc vNCcy")
place_name = address.text.split(',')[0]
print(place_name)

Ravipuram

In [68]:
#here this hmtl 'a' contain both place and city names but we need only city name 
#we need split on ',' and get first item 
adhress=soup.find('a', class_="sc-clNaTc vNCcy")
city=adhress.text.split(',')[1]
print(city)

 Kochi

In [69]:
#here this hmtl 'div', class_="sc-1q7bklc-1 cILgox" contain both dining_rating and delivery_rating but we need only dining_rating_element  
#we using len is greater than zero to get first item 
dining_rating_element = soup.find('div', class_="sc-1q7bklc-1 cILgox")
if dining_rating_element:
    print(dining_rating_element.text)
else:
    print("non")

4.6

In [78]:
#here this hmtl 'div', class_="sc-1q7bklc-1 cILgox" contain both dining_rating and delivery_rating but we need only delivery_rating 
#we using len great than one to  get second item 
delivery_rating_elements = soup.find_all('div', class_="sc-1q7bklc-1 cILgox")
if len(delivery_rating_elements) >1 :
        print(element.text)
else:
    print("non")

4.1

In [80]:
#here this hmtl 'div', class_="sc-1q7bklc-8 kEgyiI" contain both dining_votes and delivery_votes but we need only dining_votes 
dining_votes_element = soup.find('div', class_="sc-1q7bklc-8 kEgyiI")
if dining_votes_element:
    print(dining_votes_element.text)

259

In [ ]:
#here this hmtl 'div', class_="sc-1q7bklc-8 kEgyiI" contain both dining_votes and delivery_votes but we need only delivery_votes 
#we using len great than one to  get second item
delivery_votes_element = soup.find_all('div', class_="sc-1q7bklc-8 kEgyiI")
if len(delivery_votes_element) >1 :
        print(delivery_votes_element.text)
else:
    print("non")

In [ ]:
#we stored inner hmtl of page in items variable 
#we need to run a loop for getting all values from the items hmtl tags

In [ ]:
#here we get the each and every item names (dishes name) in specific restaurant 
#this 'h4', class_="sc-1s0saks-15 iSmBPS" html is present inside this code'div',class_="sc-1s0saks-11 cYGeYt" which we stored items variable
item_name_element = items.find_all('h4', class_="sc-1s0saks-15 iSmBPS")
for i in  item_name_element:
     print(i.text)

In [ ]:
#here we get the each and every  best_selling items identify best seller tag in specific restaurant 
#this 'div', class_="sc-1s0saks-2 jYdcVk" html is present inside this code'div',class_="sc-1s0saks-11 cYGeYt" which we stored items variable 
best_seller_element = items.find('div', class_="sc-1s0saks-2 jYdcVk")
for i in  item_name_element:
                print(i)

In [ ]:
#here we get the each and every  votes for each item in specific restaurant 
#this 'span', class_="sc-z30xqq-4 hTgtKb" html is present inside this code'div',class_="sc-1s0saks-11 cYGeYt" which we stored items variable 
votes_element = items.find('span', class_="sc-z30xqq-4 hTgtKb")
      for i in  item_name_element:
                     print(i)

In [ ]:
#here we get the each and every  price for each item in specific restaurant 
#this 'div', class_="sc-17hyc2s-3 jOoliK sc-1s0saks-8 gYkxGN" html is present inside this code'div',class_="sc-1s0saks-11 cYGeYt" which we stored items variable 

price_element = items.find('div', class_="sc-17hyc2s-3 jOoliK sc-1s0saks-8 gYkxGN")
           for i in  item_name_element:
                     print(i)

In [ ]:
#TO GET ALL WEB PAGES IN PARTICULAR LOCATION NEED TO FIND THE THESE TAGS 
<a href="https://www.zomato.com/hyderabad/abids-restaurants" class="sc-clNaTc vNCcy">Abids, Hyderabad</a>
URL_FIND=soup.find_all('a',class_="sc-clNaTc vNCcy")

In [54]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'
}

urls = [ 'https://www.zomato.com/kochi/al-taza-1-kaloor/order',
       'https://www.zomato.com/kochi/cafe-17-ravipuram/order']



dataframes = []

for url in urls:
    webpage = requests.get(url, headers=headers).text
    soup = BeautifulSoup(webpage, "html.parser")

    restaurant_name = []
    dining_rating = []
    delivery_rating = []
    dining_votes = []
    delivery_votes = []
    tags=[]
    item_names = []
    description =[]
    best_sellers = []
    votes = []
    prices = []
    place_name = []
    city = []
    items = soup.find_all('div', class_="sc-1s0saks-11 cYGeYt")


    for item in items:
        restaurant_element = soup.find('h1', class_="sc-7kepeu-0 sc-iSDuPN fwzNdh")
        restaurant_name.append(restaurant_element.text if restaurant_element else "non")

        dining_rating_element = soup.find('div', class_="sc-1q7bklc-1 cILgox")
        dining_rating.append(dining_rating_element.text if dining_rating_element else "non")

        delivery_rating_element = soup.find_all('div', class_="sc-1q7bklc-1 cILgox")
        if len(delivery_rating_element) > 1:
            delivery_rating.append(delivery_rating_element[1].text if delivery_rating_element[1] else "non")
        else:
            delivery_rating.append("non")

        dining_votes_element = soup.find('div', class_="sc-1q7bklc-8 kEgyiI")
        dining_votes.append(dining_votes_element.text if dining_votes_element else "non")

        delivery_votes_element = soup.find_all('div', class_="sc-1q7bklc-8 kEgyiI")
        if len(delivery_votes_element) > 1:
            delivery_votes.append(delivery_votes_element[1].text if delivery_votes_element[1] else "non")
        else:
            delivery_votes.append("non")
            
        tag_list = soup.find_all('a', class_="sc-hIVACf hAtIrI")
        for tag in tag_list:
            tags.append(tag.text if tag.text else "non")


        item_name_element = item.find('h4', class_="sc-1s0saks-15 iSmBPS")
        item_names.append(item_name_element.text if item_name_element else "non")
         
        best_seller_element = item.find('div', class_="sc-1s0saks-2 jYdcVk")
        best_sellers.append(best_seller_element.text if best_seller_element else "non")

        votes_element = item.find('span', class_="sc-z30xqq-4 hTgtKb")
        votes.append(votes_element.text if votes_element else "non")

        price_element = item.find('div', class_="sc-17hyc2s-3 jOoliK sc-1s0saks-8 gYkxGN")
        prices.append(price_element.text.split('₹')[1] if price_element else "non")

        address_element = soup.find('a', class_="sc-clNaTc vNCcy")
        address = address_element.text if address_element else "non"
        place_name.append(address.split(',')[0])
        city.append(address.split(',')[1] if len(address.split(',')) > 1 else "non")

    data = {
        'Restaurant Name': restaurant_name,
        'Dining Rating': dining_rating,
        'Delivery Rating': delivery_rating,
        'Dining Votes': dining_votes,
        'Delivery Votes': delivery_votes,
         'TAG' :tag,
        'Place Name': place_name,
        'City': city,
        'Item Name': item_names,
        'Best Seller': best_sellers,
        'Votes': votes,
        'Prices': prices
    }

    df = pd.DataFrame(data)
    dataframes.append(df)

# Print each dataframe
for i, df in enumerate(dataframes):
    print(f"Data from URL {urls[i]}:")
    print(df)
    print()

Data from URL https://www.zomato.com/kochi/al-taza-1-kaloor/order:
   Restaurant Name Dining Rating Delivery Rating Dining Votes Delivery Votes  \
0          Al Taza           4.4             4.4          367          21.8K
1          Al Taza           4.4             4.4          367          21.8K
2          Al Taza           4.4             4.4          367          21.8K
3          Al Taza           4.4             4.4          367          21.8K
4          Al Taza           4.4             4.4          367          21.8K
5          Al Taza           4.4             4.4          367          21.8K
6          Al Taza           4.4             4.4          367          21.8K
7          Al Taza           4.4             4.4          367          21.8K
8          Al Taza           4.4             4.4          367          21.8K
9          Al Taza           4.4             4.4          367          21.8K
10         Al Taza           4.4             4.4          367          21.8K
11         Al Taza           4.4             4.4          367          21.8K
12         Al Taza           4.4             4.4          367          21.8K
13         Al Taza           4.4             4.4          367          21.8K
14         Al Taza           4.4             4.4          367          21.8K
15         Al Taza           4.4             4.4          367          21.8K
16         Al Taza           4.4             4.4          367          21.8K
17         Al Taza           4.4             4.4          367          21.8K
18         Al Taza           4.4             4.4          367          21.8K
19         Al Taza           4.4             4.4          367          21.8K
20         Al Taza           4.4             4.4          367          21.8K
21         Al Taza           4.4             4.4          367          21.8K
22         Al Taza           4.4             4.4          367          21.8K
23         Al Taza           4.4             4.4          367          21.8K
24         Al Taza           4.4             4.4          367          21.8K
25         Al Taza           4.4             4.4          367          21.8K
26         Al Taza           4.4             4.4          367          21.8K
27         Al Taza           4.4             4.4          367          21.8K
28         Al Taza           4.4             4.4          367          21.8K
29         Al Taza           4.4             4.4          367          21.8K
30         Al Taza           4.4             4.4          367          21.8K
31         Al Taza           4.4             4.4          367          21.8K
32         Al Taza           4.4             4.4          367          21.8K
33         Al Taza           4.4             4.4          367          21.8K

          TAG Place Name    City                        Item Name Best Seller  \
0   Beverages     Kaloor   Kochi                Full Meat Chicken  BESTSELLER
1   Beverages     Kaloor   Kochi          Al Taza Special Chicken  BESTSELLER
2   Beverages     Kaloor   Kochi            Chicken Club Shawarma  BESTSELLER
3   Beverages     Kaloor   Kochi          Chicken Shawarma Burger  BESTSELLER
4   Beverages     Kaloor   Kochi         Chicken Healthy Shawarma  BESTSELLER
5   Beverages     Kaloor   Kochi  Al Taza Special Dry Fruit Shake         non
6   Beverages     Kaloor   Kochi                    Nutella Shake         non
7   Beverages     Kaloor   Kochi           Chicken Pizza Shawarma         non
8   Beverages     Kaloor   Kochi             Passion Fruit Mojito         non
9   Beverages     Kaloor   Kochi                  Mint Lime Juice         non
10  Beverages     Kaloor   Kochi          Al Taza Special Chicken  BESTSELLER
11  Beverages     Kaloor   Kochi            Chicken Club Shawarma  BESTSELLER
12  Beverages     Kaloor   Kochi         Chicken Healthy Shawarma  BESTSELLER
13  Beverages     Kaloor   Kochi                Full Meat Chicken  BESTSELLER
14  Beverages     Kaloor   Kochi           Chicken Pizza Shawarma         non
15  Beverages     Kaloor   Kochi          Chicken Shawarma Burger  BESTSELLER
16  Beverages     Kaloor   Kochi  Al Taza Special Dry Fruit Shake         non
17  Beverages     Kaloor   Kochi              Black Currant Shake         non
18  Beverages     Kaloor   Kochi                    Brownie Shake         non
19  Beverages     Kaloor   Kochi                    Kit Kat Shake         non
20  Beverages     Kaloor   Kochi                    Nutella Shake         non
21  Beverages     Kaloor   Kochi                       Oreo Shake         non
22  Beverages     Kaloor   Kochi                     Carrot Juice         non
23  Beverages     Kaloor   Kochi                  Mint Lime Juice         non
24  Beverages     Kaloor   Kochi                      Normal Lime         non
25  Beverages     Kaloor   Kochi                     Orange Juice         non
26  Beverages     Kaloor   Kochi                  Pineapple Juice         non
27  Beverages     Kaloor   Kochi                 Watermelon Juice         non
28  Beverages     Kaloor   Kochi             Black Current Mojito         non
29  Beverages     Kaloor   Kochi              Blue Curacao Mojito         non
30  Beverages     Kaloor   Kochi               Green Apple Mojito         non
31  Beverages     Kaloor   Kochi                      Kiwi Mojito         non
32  Beverages     Kaloor   Kochi             Passion Fruit Mojito         non
33  Beverages     Kaloor   Kochi                Watermelon Mojito         non

         Votes Prices
0   1883 votes    180
1   1191 votes    215
2    151 votes    260
3    201 votes    300
4     89 votes    260
5     73 votes    180
6     59 votes    180
7     33 votes    250
8     68 votes    120
9    137 votes     65
10  1191 votes    215
11   151 votes    260
12    89 votes    260
13  1883 votes    180
14    33 votes    250
15   201 votes    300
16    73 votes    180
17     9 votes    180
18    32 votes    180
19    48 votes    180
20    59 votes    180
21    26 votes    180
22    28 votes    130
23   137 votes     65
24   124 votes     50
25    22 votes    130
26    26 votes    130
27    16 votes    130
28         non    120
29    28 votes    120
30    45 votes    120
31     9 votes    120
32    68 votes    120
33    19 votes    120

Data from URL https://www.zomato.com/kochi/cafe-17-ravipuram/order:
    Restaurant Name Dining Rating Delivery Rating Dining Votes Delivery Votes  \
0           Cafe 17           4.6             4.1          259          4,522
1           Cafe 17           4.6             4.1          259          4,522
2           Cafe 17           4.6             4.1          259          4,522
3           Cafe 17           4.6             4.1          259          4,522
4           Cafe 17           4.6             4.1          259          4,522
..              ...           ...             ...          ...            ...
185         Cafe 17           4.6             4.1          259          4,522
186         Cafe 17           4.6             4.1          259          4,522
187         Cafe 17           4.6             4.1          259          4,522
188         Cafe 17           4.6             4.1          259          4,522
189         Cafe 17           4.6             4.1          259          4,522

           TAG Place Name    City                     Item Name Best Seller  \
0    Beverages  Ravipuram   Kochi             Veg alfredo pasta    MUST TRY
1    Beverages  Ravipuram   Kochi     Bolognaise with meatballs  BESTSELLER
2    Beverages  Ravipuram   Kochi  Tandoori chicken pizza - 10"         non
3    Beverages  Ravipuram   Kochi            Chicken parmigiana    MUST TRY
4    Beverages  Ravipuram   Kochi         Chicken alfredo pasta    MUST TRY
..         ...        ...     ...                           ...         ...
185  Beverages  Ravipuram   Kochi                Plain omelette         non
186  Beverages  Ravipuram   Kochi        Quatro chilli omelette         non
187  Beverages  Ravipuram   Kochi               Cafe 17 sunrise         non
188  Beverages  Ravipuram   Kochi                 Eggs to order         non
189  Beverages  Ravipuram   Kochi             English breakfast  BESTSELLER

        Votes Prices
0    33 votes    280
1    16 votes    340
2     6 votes    450
3    44 votes    410
4    59 votes    300
..        ...    ...
185       non    280
186       non    280
187       non    320
188       non    280
189  24 votes    380

[190 rows x 12 columns]

In [55]:
import pandas as pd

# Your previous code to scrape the data...

# Combine all dataframes into a single dataframe
combined_df = pd.concat(dataframes)

# Reset the index of the combined dataframe
combined_df.reset_index(drop=True, inplace=True)

# Print the combined dataframe
print("Combined Dataframe:")
print(combined_df)

Combined Dataframe:
    Restaurant Name Dining Rating Delivery Rating Dining Votes Delivery Votes  \
0           Al Taza           4.4             4.4          367          21.8K
1           Al Taza           4.4             4.4          367          21.8K
2           Al Taza           4.4             4.4          367          21.8K
3           Al Taza           4.4             4.4          367          21.8K
4           Al Taza           4.4             4.4          367          21.8K
..              ...           ...             ...          ...            ...
219         Cafe 17           4.6             4.1          259          4,522
220         Cafe 17           4.6             4.1          259          4,522
221         Cafe 17           4.6             4.1          259          4,522
222         Cafe 17           4.6             4.1          259          4,522
223         Cafe 17           4.6             4.1          259          4,522

           TAG Place Name    City                 Item Name Best Seller  \
0    Beverages     Kaloor   Kochi         Full Meat Chicken  BESTSELLER
1    Beverages     Kaloor   Kochi   Al Taza Special Chicken  BESTSELLER
2    Beverages     Kaloor   Kochi     Chicken Club Shawarma  BESTSELLER
3    Beverages     Kaloor   Kochi   Chicken Shawarma Burger  BESTSELLER
4    Beverages     Kaloor   Kochi  Chicken Healthy Shawarma  BESTSELLER
..         ...        ...     ...                       ...         ...
219  Beverages  Ravipuram   Kochi            Plain omelette         non
220  Beverages  Ravipuram   Kochi    Quatro chilli omelette         non
221  Beverages  Ravipuram   Kochi           Cafe 17 sunrise         non
222  Beverages  Ravipuram   Kochi             Eggs to order         non
223  Beverages  Ravipuram   Kochi         English breakfast  BESTSELLER

          Votes Prices
0    1883 votes    180
1    1191 votes    215
2     151 votes    260
3     201 votes    300
4      89 votes    260
..          ...    ...
219         non    280
220         non    280
221         non    320
222         non    280
223    24 votes    380

[224 rows x 12 columns]

In [56]:
combined_df.sample(10)

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,TAG,Place Name,City,Item Name,Best Seller,Votes,Prices
42,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Roasted tomato & basil soup.,non,20 votes,240
98,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Pineapple & peach agua fresca mocktail,non,non,190
149,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Chicken rrabiata pasta,non,non,300
180,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Teriyaki beef burger,non,non,350
77,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Pesto chicken sandwich.,non,non,300
100,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Green tea vanilla,non,non,160
144,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Bolognaise with meatballs,BESTSELLER,16 votes,340
40,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Grilled steak salad,MUST TRY,38 votes,290
115,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Oreo shake,non,9 votes,210
172,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Classic veg burger,non,6 votes,260

In [57]:
# Assuming you have a DataFrame named 'df' with a 'Votes' column
combined_df['Votes'] = combined_df['Votes'].str.replace('votes', '').str.strip()

# Print the updated DataFrame
combined_df

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,TAG,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Al Taza,4.4,4.4,367,21.8K,Beverages,Kaloor,Kochi,Full Meat Chicken,BESTSELLER,1883,180
1,Al Taza,4.4,4.4,367,21.8K,Beverages,Kaloor,Kochi,Al Taza Special Chicken,BESTSELLER,1191,215
2,Al Taza,4.4,4.4,367,21.8K,Beverages,Kaloor,Kochi,Chicken Club Shawarma,BESTSELLER,151,260
3,Al Taza,4.4,4.4,367,21.8K,Beverages,Kaloor,Kochi,Chicken Shawarma Burger,BESTSELLER,201,300
4,Al Taza,4.4,4.4,367,21.8K,Beverages,Kaloor,Kochi,Chicken Healthy Shawarma,BESTSELLER,89,260
...,...,...,...,...,...,...,...,...,...,...,...,...
219,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Plain omelette,non,non,280
220,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Quatro chilli omelette,non,non,280
221,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Cafe 17 sunrise,non,non,320
222,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,Eggs to order,non,non,280
223,Cafe 17,4.6,4.1,259,"4,522",Beverages,Ravipuram,Kochi,English breakfast,BESTSELLER,24,380

In [58]:
combined_df.replace('non', np.nan, inplace=True)

In [59]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant Name  224 non-null    object
 1   Dining Rating    224 non-null    object
 2   Delivery Rating  224 non-null    object
 3   Dining Votes     224 non-null    object
 4   Delivery Votes   224 non-null    object
 5   TAG              224 non-null    object
 6   Place Name       224 non-null    object
 7   City             224 non-null    object
 8   Item Name        224 non-null    object
 9   Best Seller      40 non-null     object
 10  Votes            117 non-null    object
 11  Prices           224 non-null    object
dtypes: object(12)
memory usage: 21.1+ KB

In [60]:
import pandas as pd

# Assuming you have a DataFrame named 'df' with the structure you mentioned

# Convert Prices column to float
combined_df['Dining Rating'] = pd.to_numeric(combined_df['Dining Rating'], errors='coerce')
combined_df['Delivery Rating'] = pd.to_numeric(combined_df['Delivery Rating'], errors='coerce')
combined_df['Prices'] = pd.to_numeric(combined_df['Prices'], errors='coerce')



# Convert Votes column to integer
combined_df['Votes'] = pd.to_numeric(combined_df['Votes'], errors='coerce').fillna(0).astype(int)
combined_df['Dining Votes'] = pd.to_numeric(combined_df['Dining Votes'], errors='coerce').fillna(0).astype(int)
combined_df['Delivery Votes'] = pd.to_numeric(combined_df['Delivery Votes'], errors='coerce').fillna(0).astype(int)

# Convert City and Place Name columns to category
combined_df['City'] = combined_df['City'].astype('category')
combined_df['Place Name'] = combined_df['Place Name'].astype('category')
combined_df['TAG'] = combined_df['TAG'].astype('category')

In [61]:
combined_df

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,TAG,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Al Taza,4.4,4.4,367,0,Beverages,Kaloor,Kochi,Full Meat Chicken,BESTSELLER,1883,180
1,Al Taza,4.4,4.4,367,0,Beverages,Kaloor,Kochi,Al Taza Special Chicken,BESTSELLER,1191,215
2,Al Taza,4.4,4.4,367,0,Beverages,Kaloor,Kochi,Chicken Club Shawarma,BESTSELLER,151,260
3,Al Taza,4.4,4.4,367,0,Beverages,Kaloor,Kochi,Chicken Shawarma Burger,BESTSELLER,201,300
4,Al Taza,4.4,4.4,367,0,Beverages,Kaloor,Kochi,Chicken Healthy Shawarma,BESTSELLER,89,260
...,...,...,...,...,...,...,...,...,...,...,...,...
219,Cafe 17,4.6,4.1,259,0,Beverages,Ravipuram,Kochi,Plain omelette,NaN,0,280
220,Cafe 17,4.6,4.1,259,0,Beverages,Ravipuram,Kochi,Quatro chilli omelette,NaN,0,280
221,Cafe 17,4.6,4.1,259,0,Beverages,Ravipuram,Kochi,Cafe 17 sunrise,NaN,0,320
222,Cafe 17,4.6,4.1,259,0,Beverages,Ravipuram,Kochi,Eggs to order,NaN,0,280
223,Cafe 17,4.6,4.1,259,0,Beverages,Ravipuram,Kochi,English breakfast,BESTSELLER,24,380

In [ ]:
# Assuming you have created the DataFrame 'df' from your data

combined_df.to_excel('webscraping_data.xlsx', index=False)

import os

# Assuming you have created the DataFrame 'df' from your data

output_dir = 'C://Users//****//***//Desktop//web_scraping'
output_file = os.path.join(output_dir, 'webscraping_data.xlsx')

combined_df.to_excel(output_file, index=False)